-- CI / local bootstrap: runtime role must NOT bypass RLS.
-- Run as migrator/superuser AFTER drizzle migrations.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'dang_runtime') THEN
    CREATE ROLE dang_runtime
      LOGIN
      PASSWORD 'dang_runtime_ci'
      NOSUPERUSER
      NOCREATEDB
      NOCREATEROLE
      NOINHERIT
      NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE dang_test TO dang_runtime;

GRANT USAGE ON SCHEMA
  iam, audit, app, accounting, finance, collab, procurement, asset, partnership, personal, proposals
TO dang_runtime;

-- Broad DML for app tables; revokes below restore ledger/audit immutability.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA iam TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA accounting TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA finance TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA collab TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA procurement TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA asset TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA partnership TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA personal TO dang_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA proposals TO dang_runtime;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA iam TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA audit TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA accounting TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA finance TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA collab TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA procurement TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA asset TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA partnership TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA personal TO dang_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA proposals TO dang_runtime;

ALTER DEFAULT PRIVILEGES IN SCHEMA iam GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA accounting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA collab GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA personal GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA proposals GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dang_runtime;

REVOKE UPDATE, DELETE ON audit.event FROM dang_runtime;
REVOKE UPDATE, DELETE ON accounting.journal_entry, accounting.journal_line FROM dang_runtime;
